<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('chat_histories', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('user_id'); // the tenant/shop
            $table->string('phone'); // the customer phone number
            $table->string('role'); // user, assistant, system, tool
            $table->longText('content')->nullable(); // the actual text
            $table->string('tool_call_id')->nullable(); // id generated by OpenAI
            $table->string('tool_name')->nullable(); // the tool that was called
            $table->timestamp('timestamp')->useCurrent(); // for logic
            $table->timestamps();
            
            $table->index(['user_id', 'phone']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('chat_histories');
    }
};
